run:
  deadline: 10m

output:
  formats: colored-line-number

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - durationcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - grouper
    - ineffassign
    - makezero
    - nosprintfhostport
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - typecheck
    - unconvert
