#!/bin/bash
set -e

go build -tags harness

case $1 in

  dcrbtc)
    ./simnet-trade-tests --base1node trading1 --base2node trading2 ${@:2}
    ;;

  dcrspvbtc)
    ./simnet-trade-tests --base1node trading1 --base2node trading2 -base1type spv ${@:2}
    ;;

  dcrbtcspv)
    ./simnet-trade-tests --base1node trading1 --base2node trading2 --quote1type spv ${@:2}
    ;;

  dcrbtcelectrum)
    ./simnet-trade-tests --base1node trading1 --base2node trading2 --quote1type electrum ${@:2}
    ;;

  bchdcr)
    ./simnet-trade-tests --base bch --quote dcr --quote1node trading1 --quote2node trading2 \
		--regasset dcr ${@:2}
    ;;

  bchspvdcr)
    ./simnet-trade-tests --base bch --quote dcr --quote1node trading1 --quote2node trading2 \
		--regasset dcr --base1type=spv ${@:2}
    ;;

  ltcdcr)
    ./simnet-trade-tests --base ltc --quote dcr --quote1node trading1 --quote2node trading2 \
		--regasset dcr ${@:2}
    ;;

  ltcspvdcr)
    ./simnet-trade-tests --base ltc --quote dcr --quote1node trading1 --quote2node trading2 \
		--regasset dcr --base1type spv ${@:2}
    ;;

  ltcelectrumdcr)
    ./simnet-trade-tests --base ltc --quote dcr --quote1node trading1 --quote2node trading2 \
		--base1type electrum --regasset dcr ${@:2}
    ;;

  dcrdash)
    ./simnet-trade-tests --base1node trading1 --base2node trading2 \
                         --quote dash \
                         --quote1node gamma --quote2node delta ${@:2}
    ;;

  dcrdoge)
    ./simnet-trade-tests --base1node trading1 --base2node trading2 --quote doge ${@:2}
    ;;

  dcrdgb)
    ./simnet-trade-tests --base1node trading1 --base2node trading2 --quote dgb ${@:2}
    ;;

  dcreth)
    ./simnet-trade-tests --base1node trading1 --base2node trading2 --quote eth ${@:2}
    ;;

  dcrfiro)
    ./simnet-trade-tests --base1node trading1 --base2node trading2 --quote firo ${@:2}
    ;;

  dcrfiroelectrum)
    ./simnet-trade-tests --base1node trading1 --base2node trading2 --quote firo --quote1type electrum ${@:2}
    ;;

  zecbtc)
    ./simnet-trade-tests --base zec --quote btc --regasset btc ${@:2}
    ;;

  dcrdextt)
    ./simnet-trade-tests --base1node trading1 --base2node trading2 --quote dextt.eth ${@:2}
    ;;

  polygondcr)
    ./simnet-trade-tests --quote1node trading1 --quote2node trading2 --quote dcr --base polygon --regasset dcr ${@:2}
    ;;

  polydexttdcr)
    ./simnet-trade-tests --quote1node trading1 --quote2node trading2 --base dextt.polygon --quote dcr --regasset dcr  ${@:2}
    ;;

  zclbtc)
    ./simnet-trade-tests --base zcl --quote btc --regasset btc ${@:2}
    ;;

  help|--help|-h)
    ./simnet-trade-tests --help
    cat <<EOF

---------------------

The following pre-configured tests are available. Be sure to run the appropriate harnesses before starting the dcrdex server harness.

dcrbtc - RPC wallets on DCR-BTC market
dcrspvbtc - Decred SPV wallet and Bitcoin RPC wallet on DCR-BTC
dcrbtcspv - Decred RPC wallet and Bitcoin SPV wallet on DCR-BTC market
dcrbtcelectrum - Decred RPC wallet and Bitcoin Electrum wallet on DCR-BTC market
bchdcr - RPC wallets on BCH-DCR market
bchspvdcr - Bitcoin Cash SPV wallet and Decred RPC Wallet on BCH-DCR market
ltcdcr - RPC wallets on LTC-DCR market
ltcspvdcr - Litecoin SPV wallet and Decred RPC Wallet on LTC-DCR market
ltcelectrumdcr - Litecoin Electrum wallet and Decred RPC wallet on LTC-DCR market
dcrdash - RPC wallets on DCR-DASH market
dcrdoge - RPC wallets on DCR-DOGE market
dcrdgb - RPC wallets on DCR-DGB market
dcreth - Decred RPC wallet and Ethereum RPC wallet on DCR-ETH market
dcrfiro - RPC wallets on DCR-FIRO market
dcrfiroelectrum - Decred RPC wallet and Firo Electrum wallet on DCR-FIRO market
zecbtc - RPC wallets on ZEC-BTC market
dcrdextt - Decred RPC wallet and Ethereum wallet with dextt.eth test token on market DCR-DEXTT.ETH
polygondcr - Decred RPC wallet and Polygon RPC wallet on POLYGON-DCR market
polydexttdcr - Decred RPC wallet and Polygon wallet with dextt.polygon test token on market DEXTT.POLYGON-DCR
zclbtc - Zclassic RPC wallet and Bitcoin RPC wallet on ZCL-BTC

---------------------

One or more of the following tests can be run by specifying one or more -t flags. Default is ['success']. All tests for an asset pair can be run with --all. When using --all, tests can be excluded with --except=test_name.

EOF

    ./simnet-trade-tests --list
    ;;

  list|--list) # otherwise you get 'unknown program'. probably a smell for bad design on my part.
    ./simnet-trade-tests --list
    ;;

  *)
    echo "unknown program"
    ;;
esac
